### ISSUE TITLE
Reference to Propreitary

### ISSUE THREAD

**Issue by xnox** [microsoft/ASRDFD#4]
https://github.com/microsoft/ASRDFD/blob/6c7a879b9053b2d3d397d07d196cd05237914c5f/src/filter_host.c#L3507

The above file mentioned the module is Propreitary (note typo) and taints the kernel,

yet at https://github.com/microsoft/ASRDFD/blob/6c7a879b9053b2d3d397d07d196cd05237914c5f/src/filter_host.c#L3683 license is GPLv2.

Is the Propreitary message out of date?

**Comment by lmuppa** [comment]
Removed the logging as that is no more needed with GPL driver code.
