### ISSUE TITLE
Microsoft vs InMage Systems Pvt Ltd metadate details out of date?

### ISSUE THREAD

**Issue by xnox** [microsoft/ASRDFD#5]
https://github.com/microsoft/ASRDFD/blob/6c7a879b9053b2d3d397d07d196cd05237914c5f/src/filter_host.c#L3681

The copyright at the top of the file states Microsoft, yet module metadata lists "InMage Systems Pvt Ltd" as author. Is the module metadata out of date?

**Comment by lmuppa** [comment]
Updated the metadata to point to Microsoft.
